default_agent: device_agent_07_aug_4
agents:
  device_agent_07_aug_4:
    name: device_agent_07_aug_4
    entrypoint: /Users/vgodwin/genesis-test/agent-runtime/device_management/samples/02-use-cases/05-Device-Management-System/agent-runtime/strands_agent_runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::288947426911:role/AgentGatewayAccessRole
      account: '288947426911'
      region: us-west-2
      ecr_repository: 288947426911.dkr.ecr.us-west-2.amazonaws.com/bedrock_agentcore-device_agent_07_aug_4
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: device_agent_07_aug_4-WHWWbI2v35
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:288947426911:runtime/device_agent_07_aug_4-WHWWbI2v35
      agent_session_id: b5248e19-b5fb-448d-8a7f-528999cede24
    authorizer_configuration: null
    oauth_configuration: null
